### ISSUE TITLE
Alaska English not showing up

### ISSUE THREAD

**Issue by brendanbabb** [daguar/balance-metrics-rails#27]
Not sure why, but Alaska English statistics are not showing up. But Alaska Spanish our.

**Comment by daguar** [comment]
I actually was doing some maintenance this weekend and noticed the same thing and already have a fix ready! The issue — as is generally the case with this hacked-together metrics app — is that we just did something early on that no longer applies. So, we used to be able to rely on a single call to Twilio to get phone numbers but they paginate by 50 and we now have >50. Fix coming shortly.

**Comment by daguar** [comment]
Fix is live!

**Comment by brendanbabb** [comment]
Thanks!
